version: "3.9"
services:
  app:
    build:
      context: app
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: ${LOCAL_WORKSPACE_FOLDER:-.}/app
        target: /app
    command: yarn dev
    ports:
      - 3000:3000
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/ecommerce_db
      - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
      - BACKEND_URL=http://backend:8080
    networks:
      - myapp
    depends_on:
      - db
      - backend
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: ${LOCAL_WORKSPACE_FOLDER:-.}/backend
        target: /app
    command: yarn start:dev
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/ecommerce_db
      - PORT=8080
    networks:
      - myapp
    depends_on:
      - db
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ecommerce_db
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - myapp

volumes:
  postgres_data:

networks:
  myapp:
    name: myapp
    driver: overlay
